---
username: "rubemlrm"
user_group: "rubemlrm"
home_dir: "/home/rubemlrm/"
git_email: rubemmota89@gmail.com
git_name: "Rubem Mota"
use_firewall: true
use_openssh: true
use_fail2ban: true
use_docker: true
use_desktop: true
use_php: true
use_python: true
use_nodejs: true
use_kubernetes: true
ssh_port: 22
use_nvidia: true
use_gnome: false
gnome_extensions:
  - id: 517
    enable: yes
  - id: 1160
    enable: no
  - id: 615
    enable: yes
  - id: 307
    enable: yes
  - id: 36
    enable: yes
gnome_user: "{{ username }}"
gnome_dconf:
  #Nautilus (File Manager) Usability
  - key: "/org/gtk/Settings/FileChooser/sort-directories-first"
    value: true
  - key: "/org/gnome/nautilus/list-view/use-tree-view"
    value: true
  #window switcher
  - key: "/org/gnome/shell/window-switcher/current-workspace-only"
    value: true
gnome_gsettings:
  - schema: org.gnome.settings-daemon.plugins.media-keys
    key: home
    value: "\"['<Super>e']\""
  - schema: org.gnome.desktop.interface
    key: icon-theme
    value: "Papirus"
  - schema: org.gnome.desktop.interface
    key: gtk-theme
    value: "Numix"
  - schema: org.gnome.desktop.interface
    key: monospace-font-name
    value: "'Fira Mono Medium 8'"
  - schema: org.gnome.desktop.interface
    key: document-font-name
    value: "'Noto Sans 8'"
  - schema: org.gnome.desktop.interface
    key: font-name
    value: "'Noto Sans,  10'"
  - schema: org.gnome.desktop.interface
    key: toolbar-style
    value: "text"
  - schema: org.gnome.desktop.interface
    key: color-scheme
    value: "prefer-dark"
  - schema: org.gnome.desktop.interface
    key: cursor-size
    value: "24"
  - schema: org.gnome.desktop.interface
    key: cursor-theme
    value: "Paper"
  - schema: org.gnome.desktop.interface
    key: font-hinting
    value: "full"
  - schema: org.gnome.desktop.wm.preferences
    key: button-layout
    value: "icon:minimize,maximize,close"
  - schema: org.gnome.desktop.wm.preferences
    key: num-workspaces
    value: "2"
  - schema: org.gnome.desktop.wm.preferences
    key: titlebar-font
    value: "'Noto Sans 9'"
  - schema: org.gnome.desktop.datetime
    key: automatic-timezone
    value: "true"
  - schema: org.gnome.shell.extensions.dash-to-dock
    schemadir: ~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas
    key: apply-custom-theme
    value: "true"
  - schema: org.gnome.shell.extensions.dash-to-dock
    schemadir: ~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas
    key: custom-theme-shrink
    value: "true"
  - schema: org.gnome.shell.extensions.dash-to-dock
    schemadir: ~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas
    key: dash-max-icon-size
    value: "32"
  - schema: org.gnome.shell.extensions.dash-to-dock
    schemadir: ~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas
    key: isolate-monitors
    value: "true"
  - schema: org.gnome.shell.extensions.dash-to-dock
    schemadir: ~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas
    key: isolate-workspaces
    value: "true"
  - schema: org.gnome.shell.extensions.dash-to-dock
    schemadir: ~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas
    key: multi-monitor
    value: "true"
  - schema: org.gnome.shell.extensions.dash-to-dock
    schemadir: ~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas
    key: show-mounts-network
    value: "true"
