- name: "DNF test - check copr repo"
  ansible.builtin.dnf:
    name: ["fedora-workstation-repositories"]
    state: present
  check_mode: yes
  register: dnf_copr_status
- name: "DNF test - assert dnf_copr_status"
  ansible.builtin.assert:
    that:
      - not dnf_copr_status.changed
- name: "DNF test - check package status"
  ansible.builtin.dnf:
    name: "abrt-gui"
    state: "absent"
  check_mode: yes
  register: pkg_status
- name: "DNF test - package is installed"
  ansible.builtin.assert:
    that:
      - not pkg_status.changed
