- name: "Docker test - check package status"
  ansible.builtin.package:
    name: "docker-ce"
    state: "present"
  check_mode: true
  register: pkg_status
- name: "Docker test - assert package is installed"
  ansible.builtin.assert:
    that:
      - not pkg_status.changed
- name: "Docker test - check service status"
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  check_mode: true
  register: service_status
- name: "Docker test - assert service is started"
  ansible.builtin.assert:
    that:
      - not service_status.changed
- name: "Docker test - check if user is on docker group"
  ansible.builtin.user:
    name: '{{ username }}'
    groups: docker
    append: true
  check_mode: true
  register: user_in_group_status
- name: "Docker test - assert if user is on docker group"
  ansible.builtin.assert:
    that:
      - not user_in_group_status.changed
