- name: "Python test - check if pip package is installed"
  ansible.builtin.package:
    name: "python3-pip"
    state: "present"
  check_mode: yes
  register: pip_package_status
- name: "Python test - assert pip package is installed"
  ansible.builtin.assert:
    that:
      - not pip_package_status.changed
