---
cli_base_packages:
  - vim
  - git
  - tmux
  - base-devel
  - binutils
  - make
  - gcc
  - fakeroot
  - powerline
  - powerline-vim
  - powerline-fonts
  - screenfetch
  - scrot
  - rxvt-unicode
  - bashtop
  - nano
  - wget
  - curl
  - rsync
  - shellcheck
  - intel-ucode
  - ufw
  - linux-headers
  - netctl
  - wpa_supplicant
  - dotnet-runtime
  - dotnet-sdk
  - netctl
  - openvpn
  - cronie
  - stow
  - neovim
  - mkinitcpio
  - lvm2
  - vi
  - dhcpcd
  - os-prober
  - zsh
  - python-pip
  - gnome-keyring
  - libsecret
  - ripgrep
  - lazygit
  - python-pre-commit
  - hunspell
  - hunspell-en_US
  - smartmontools
  - usbutils
  - acpid
  - acpi
  - powertop
  - linux-lts
  - cmake

cli_font_packages:
  - adobe-source-code-pro-fonts
  - ttf-fira-code
  - ttf-hack
  - ttf-fira-sans
  - ttf-font-awesome
  - otf-font-awesome
  - ttf-jetbrains-mono
  - terminus-font
  - noto-fonts
  - ttf-dejavu
  - ttf-liberation
  - ttf-droid
  - ttf-ubuntu-font-family
  - nerd-fonts
