---
common_cli_base_packages:
  - vim
  - git
  - tmux
  - base-devel
  - binutils
  - make
  - gcc
  - fakeroot
  - powerline
  - powerline-vim
  - powerline-fonts
  - screenfetch
  - scrot
  - rxvt-unicode
  - bashtop
  - nano
  - wget
  - curl
  - rsync
  - shellcheck
  - intel-ucode
  - ufw
  - linux-headers
  - netctl
  - wpa_supplicant
  - dotnet-runtime
  - dotnet-sdk
  - netctl
  - openvpn
  - cronie
  - stow
  - neovim
  - mkinitcpio
  - lvm2
  - vi
  - dhcpcd
  - os-prober
  - zsh
  - python-pip
  - gnome-keyring
  - libsecret
  - ripgrep
  - neovim
  - iwd
  - unzip
  - python-pynvim
  - python-virtualenv
  - python-setuptools
  - libfido2
  - rubygems
  - go
  - make
  - cmake
  - linux-lts
  - lua-language-server
  - ansible-language-server
  - yaml-language-server
  - bash-language-server
  - lazygit

common_cli_font_packages:
  - adobe-source-code-pro-fonts
  - ttf-fira-code
  - ttf-hack
  - ttf-fira-sans
  - ttf-font-awesome
