---
- name: Setup PC
  hosts: all
  become: true
  pre_tasks:
    - name: Load default vars file
      ansible.builtin.include_vars:
        dir: "host_vars/"
        files_matching: all.yml
  roles:
    - role: users
    - role: pacman
    - role: cli
    - role: fail2ban
      when: use_fail2ban
    - role: firewall
      when: use_firewall
    - role: openssh
      when: use_openssh
    - role: docker
      when: use_docker
    - role: samba
      when: use_samba
    - role: nodejs
      when: use_nodejs
    - role: php
      when: use_php
    - role: python
      when: use_python
    - role: golang
    - role: kubernetes
      when: use_kubernetes
    - role: desktop
      when: use_desktop
