---

- name: Setup PC
  hosts: all
  become: true
  pre_tasks:
    - name: Load default vars file
      ansible.builtin.include_vars:
        dir: "host_vars/"
        files_matching: all.yml
  roles:
    - users
    - role: petermosmans.customize-gnome
      when: use_gnome
