---
- name: Install desktop packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ desktop_packages }}"
  when: desktop_packages is defined
- name: Install themes
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ desktop_themes }}"
  when: desktop_themes is defined
