---
- name: Setup snap
  block:
  - name: Install snap
    become: true
    become_user: '{{ username }}'
    kewlfft.aur.aur:
      use: yay
      name: 'snapd'
  - name: 'Fix snap symlink'
    ansible.builtin.file:
      src: "/var/lib/snapd/snap"
      dest: "/snap"
      state: link
    notify:
    - Restart snapd
  - name: 'Install with snap'
    community.general.snap:
      name: "{{ item.name }}"
      classic: "{{ item.classic }}"
    with_items: '{{ desktop_snap_packages }}'
    when: desktop_snap_packages is defined
