---
- name: Allow non-root user access to NetworkManager
  ansible.builtin.template:
    src: network_manager_polkit.j2
    dest: /etc/polkit-1/rules.d/10-network-manager.pkla
    mode: 0644
- name: Change default target to graphical.target
  ansible.builtin.file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link
