---
- name: Archlinux - Install nodejs
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ nodejs_packages }}"

- name: Setup Javascript environment
  community.general.npm:
    name: "{{ item }}"
    state: present
    global: true
  with_items: "{{ nodejs_tools }}"

- name: Set standard npmrc rules
  ansible.builtin.template:
    src: npmrc.j2
    dest: "{{ home_dir }}.npmrc"
    owner: "{{ username }}"
    group: "{{ user_group }}"
    mode: "0600"
    follow: true
