---
- name: Fedora - Install nodejs
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ nodejs_packages }}"

- name: Setup Javascript environment
  community.general.npm:
    name: "{{ item }}"
    state: present
    global: true
  with_items: "{{ nodejs_tools }}"
