---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: instance
  vars_files:
    - test_data/testing.yml
  tasks:
    - name: Import common_cli tests
      ansible.builtin.import_tasks: ./roles_test/cli_test.yml
    - name: Import docker tests
      ansible.builtin.import_tasks: ./roles_test/docker_test.yml
      when: use_docker is true
    - name: Import firewall tests
      ansible.builtin.import_tasks: ./roles_test/firewall_test.yml
    - name: Import GoLang tests
      ansible.builtin.import_tasks: ./roles_test/golang_test.yml
    - name: Import Kubernetes tests
      ansible.builtin.import_tasks: ./roles_test/kubernetes_test.yml
    - name: Import Nodejs tests
      ansible.builtin.import_tasks: ./roles_test/nodejs_test.yml
    - name: Import Openssh tests
      ansible.builtin.import_tasks: ./roles_test/openssh_test.yml
    - name: Import fail2ban tests
      ansible.builtin.import_tasks: ./roles_test/fail2ban_test.yml
    - name: Import PHP tests
      ansible.builtin.import_tasks: ./roles_test/php_test.yml
    - name: Import Python tests
      ansible.builtin.import_tasks: ./roles_test/python_test.yml
