---
- name: Setup homebrew
  block:
    - name: Ensuring Homebrew Is Installed
      ansible.builtin.stat:
        path: /opt/homebrew/bin/brew
      register: homebrew_check

    - name: Installing Homebrew
      ansible.builtin.shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      when:
        - not homebrew_check.stat.exists
      tags:
        - skip_ansible_lint
    - name: Install cask
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items:
        - font-source-code-pro
        - font-fira-code
      become: true
      become_user: "{{ username }}"
