---
- name: Setup Pacman
  block:
    - name: Check if package exists
      ansible.builtin.package:
        name: "tmux"
        state: "present"
      check_mode: true
      register: pkg_status

    - name: Update Cache
      community.general.pacman:
        update_cache: true
      when: pkg_status.changed
      changed_when: false
      tags:
        - skip_ansible_lint

    - name: Install pacman tools
      ansible.builtin.package:
        name: '{{ item }}'
        state: present
      with_items:
        - pacman-contrib
        - base-devel
        - cronie
        - reflector
        - git
        - make 

    - name: Copy Custom pacman.conf
      ansible.builtin.template:
        src: pacman.conf.j2
        dest: /etc/pacman.conf
        mode: '0644'
        owner: 'root'
        group: 'root'

    - name: Update reflector configuration file
      ansible.builtin.template:
        src: reflector.conf.j2
        dest: /etc/xdg/reflector/reflector.conf
        mode: 0644

    - name: Allow the user to run `sudo pacman` without a password
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: '{{ username }} ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        mode: 0644
        create: true
        validate: 'visudo -cf %s'

    - name: Start systemd service - systemd-boot-update.service
      ansible.builtin.systemd:
        name: systemd-boot-update.service
        state: started
        enabled: true

    - name: Start paccache  service
      ansible.builtin.systemd:
        name: paccache.timer
        state: started
        enabled: true

    - name: Upgrade system
      community.general.pacman:
        upgrade: true
        update_cache: true

- name: Setup yay aur helper
  become: true
  become_user: '{{ username }}'
  block:
    - name: Clone Yay repo
      ansible.builtin.git:
        repo: https://aur.archlinux.org/yay.git
        dest: '{{ home_dir }}/.bin/yay'
      tags:
        - skip_ansible_lint
    - name: Check Yay Existance
      ansible.builtin.shell: command -v yay >/dev/null 2>&1
      register: yay_exists
      ignore_errors: true
      changed_when: false
    - name: Compile Yay
      ansible.builtin.command:
        chdir: "{{ home_dir }}/.bin/yay"
        cmd: "makepkg -sfi --noconfirm"
        creates: /usr/bin/yay
      when: yay_exists
      
