---
- name: "Fedora - Set minikube repo"
  block:
    - name: "Set Repo files"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "/etc/yum.repos.d/{{ item.dest }}"
        mode: 0644
      with_items:
        - src: fedora-kubernetes.repo
          dest: kubernetes.repo
    - name: "Install remote rpm's"
      ansible.builtin.yum:
        name: https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm
        state: present
        disable_gpg_check: true
    - name: "Set copr repos"
      community.general.copr:
        state: enabled
        name: "{{ item }}"
      with_items: "{{ kubernetes_copr_repos }}"
    - name: Install cli utils
      ansible.builtin.package:
        name: "{{ item }}"
      with_items: "{{ kubernetes_packages }}"
    - name: Check if helm is installed
      ansible.builtin.stat:
        path: "/usr/local/bin/helm"
      register: helm_stat_results
      changed_when: false
      ignore_errors: true
    - name: Install helm
      ansible.builtin.raw: "curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash"
      when: not helm_stat_results.stat.exists
      tags:
        - skip_ansible_lint

- name: Install helm plugins
  become: true
  become_user: "{{ username }}"
  block:
    - name: Check if helm is installed
      ansible.builtin.raw: "helm plugin list | grep {{ item.name }}"
      register: stat_results
      ignore_errors: true
      changed_when: false
      with_items: "{{ kubernetes_helm_plugins }}"
    - name: Install helm plugins
      ansible.builtin.command: "helm plugin install {{ item.item.repo }}"
      with_items: "{{ stat_results.results }}"
      when: item.stdout == ""
      tags:
          - skip_ansible_lint
