---
- name: Setup ZSH
  become: true
  become_user: '{{ username }}'
  block:
    - name: Check if Oh MY ZSH is already installed
      ansible.builtin.stat:
        path: "{{ home_dir }}.oh-my-zsh"
      register: oh_my_zsh_installed
      changed_when: false
    - name: Install Oh MY ZSH
      ansible.builtin.raw: sh -c 'curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh'
      when: not oh_my_zsh_installed.stat.exists
      tags:
        - skip_ansible_lint
    - name: Install Oh My ZSH Plugins
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ home_dir }}{{ item.dest }}"
        version: "{{ item.version }}"
      with_items: "{{ users_zsh_plugins }}"
    - name: Clone cli utils
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        version: "{{ item.version }}"
      with_items:
        - repo: 'https://github.com/junegunn/fzf.git'
          dest: "{{ home_dir }}.fzf"
          version: "0.29.0"
    - name: Setup fzf key bindings
      ansible.builtin.stat:
        path: "{{ home_dir }}.fzf.zsh"
      register: fzf_installed
      changed_when: false
    - name: Install FZF
      ansible.builtin.raw: sh -c 'bash {{ home_dir }}.fzf/install --key-bindings --completion --update-rc'
      when: not fzf_installed.stat.exists
      tags:
        - skip_ansible_lint
