---
- name: Archlinux Based - Pre-Setup Docker service
  block:
    - name: Install containers packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - docker
        - docker-compose
    - name: 'Start docker'
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true
    - name: 'Add user to docker group'
      ansible.builtin.user:
        name: '{{ username }}'
        groups: docker
        append: true
