---
- name: Install base packages
  block:
    - name: Install cli utils
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items: "{{ common_cli_base_packages }}"
    - name: Install fonts
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items: "{{ common_cli_font_packages }}"
